$(document).ready(function(){var yheight=getScrollTop();var divobj=$(".headerah");var top=parseInt(yheight);if(top>=40){divobj.css('top','0px');}else{divobj.attr('style',"");}
$('.web_xs').hover(function(){$(this).find('.web_xsbg').show();},function(){$(this).find('.web_xsbg').hide();})
$(".web_tabo .web_tabsx").attr("id",function(){return idNumber("No")+$(".web_tabo .web_tabsx").index(this)});$("ul.menu1 li").hover(function(){var c=$("ul.menu1 li");var index=c.index(this);var p=idNumber("No");show(c,index,p);});function show(controlMenu,num,prefix){var content=prefix+num;$('#'+content).siblings().hide();$('#'+content).show();controlMenu.eq(num).addClass("current").siblings().removeClass("current");};function idNumber(prefix){var idNum=prefix;return idNum;};$(".web_zcbox").hover(function(){},function(){$(".web_agh").find(".web_aghax").hide();$(".web_agh").find("ul.menu1 li").removeClass("current");});$('.web_lbkc li dl dd em').click(function(){$(this).toggleClass("phpshouchang");});$("ul.menu2 li:first-child").addClass("current");$(".content2 .layout2").attr("id",function(){return idNumber("menu")+$(".content2 .layout2").index(this)});$("ul.menu2 li").click(function(){var c=$("ul.menu2 li");var index=c.index(this);var p=idNumber("menu");show(c,index,p);});function show(controlMenu,num,prefix){var content=prefix+num;$('#'+content).siblings().hide();$('#'+content).show();controlMenu.eq(num).addClass("current").siblings().removeClass("current");};function idNumber(prefix){var idNum=prefix;return idNum;};$("ul.menu3 li:first-child").addClass("current");$(".content3 .layout3").attr("id",function(){return idNumber("fudong")+$(".content3 .layout3").index(this)});$("ul.menu3 li").hover(function(){var c=$("ul.menu3 li");var index=c.index(this);var p=idNumber("fudong");show(c,index,p);});function show(controlMenu,num,prefix){var content=prefix+num;$('#'+content).siblings().hide();$('#'+content).show();controlMenu.eq(num).addClass("current").siblings().removeClass("current");};function idNumber(prefix){var idNum=prefix;return idNum;};$(window).scroll(function(){var wheight=$(window).height();var yheight=getScrollTop();var divobj=$(".headerah");var top=parseInt(yheight);if(top>=40){divobj.css('top','0px');}else{divobj.attr('style',"");}
var height=document.documentElement.clientHeight
if(yheight>height){$(".web-xstop").show();}else{$(".web-xstop").hide();}
$('.webtoday').each(function(index){var boxtop=$(this).offset().top;if(index==0){if(boxtop>yheight){$('.web_rightlb li a').removeClass('lockup');}}
if(boxtop>yheight&&boxtop<yheight+1/3*wheight){$('.web_rightlb li a').removeClass('lockup');$('.web_rightlb li:eq('+index+') a').addClass('lockup');return false;}})})
function getScrollTop(){var scrollPos;if(window.pageYOffset){scrollPos=window.pageYOffset;}
else if(document.compatMode&&document.compatMode!='BackCompat')
{scrollPos=document.documentElement.scrollTop;}
else if(document.body){scrollPos=document.body.scrollTop;}
return scrollPos;}
var anifun=setInterval(autoatoutiao,1000);$(".web_tout .cont2 em").children("li").hover(function(){clearInterval(anifun);},function(){anifun=setInterval(autoani,1000);})
function autoatoutiao(){var a=$("i:first",".web_tout .cont2 em").clone();var aheight=$("i:first",".web_tout .cont2 em").height();var atop=-41;if(aheight>46){atop=-61;}
$("i:first",".web_tout .cont2 em").animate({"margin-top":atop+"px"},2000,function(){$("i:first",".web_tout .cont2 em").remove();a.appendTo(".web_tout .cont2 em");})}
var screenwidth=window.screen.width;if(screenwidth<=1366){$(".web_right").hide();}
$(".web_serch .text1").on("input",function(){if($(this).val()!=''){$(this).css("color","#333333");}else{$(this).css("color","#999999");}})})